"""empty message

Revision ID: 714be168693b
Revises: 
Create Date: 2020-06-26 17:20:54.879366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714be168693b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_user_id', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
