"""empty message

Revision ID: 89f839a38346
Revises: e73b6ab5d976
Create Date: 2020-07-01 18:12:47.281871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f839a38346'
down_revision = 'e73b6ab5d976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envsensor',
    sa.Column('data_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Float(precision=255), nullable=False),
    sa.Column('temperature', sa.Float(precision=255), nullable=False),
    sa.Column('humidity', sa.Float(precision=255), nullable=False),
    sa.Column('light', sa.Float(precision=255), nullable=False),
    sa.Column('heat', sa.Float(precision=255), nullable=False),
    sa.Column('di', sa.Float(precision=255), nullable=False),
    sa.Column('noise', sa.Float(precision=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('data_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('envsensor')
    # ### end Alembic commands ###
